version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: shinomontaz_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tire_storage

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shinomontaz_backend
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=tire_storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shinomontaz_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://baseshinomontaz.ru/api

  nginx:
    image: nginx:alpine
    container_name: shinomontaz_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data: