name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@83.222.18.104 '
          cd /opt/shinomontaz &&
          git config pull.rebase false &&
          git fetch origin &&
          git reset --hard origin/main &&
          docker-compose down &&
          docker-compose build --no-cache &&
          docker-compose up -d &&
          docker system prune -f
        '

    - name: Health check
      run: |
        sleep 30
        curl -f http://baseshinomontaz.ru/ || curl -f https://baseshinomontaz.ru/api/health || exit 1

    - name: Notify success
      if: success()
      run: echo "✅ Deployment successful!"

    - name: Notify failure
      if: failure()
      run: echo "❌ Deployment failed!"